org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=gunsrpg
mod_name=Guns RPG
mod_license=All Rights Reserved
mod_version=1.20.1-0.1.0-port

mod_group_id=com.wf.firearms

configuration_file_id=4608425
jei_version=15.20.0.130
