package dev.toma.gunsrpg.common.init;

import dev.toma.gunsrpg.GunsRPG;
import dev.toma.gunsrpg.common.item.*;
import dev.toma.gunsrpg.common.item.guns.GunItem;
import dev.toma.gunsrpg.common.item.guns.ammo.ItemAmmo;
import net.minecraftforge.fml.common.registry.GameRegistry;

@GameRegistry.ObjectHolder(GunsRPG.MODID)
public class GRPGItems {
    public static final GunItem PISTOL = null;
    public static final GunItem SMG = null;
    public static final GunItem ASSAULT_RIFLE = null;
    public static final GunItem SNIPER_RIFLE = null;
    public static final GunItem SHOTGUN = null;
    public static final GunItem CROSSBOW = null;
    public static final GRPGItem AMETHYST = null;
    public static final DebuffHeal ANTIDOTUM_PILLS = null;
    public static final DebuffHeal VACCINE = null;
    public static final DebuffHeal PLASTER_CAST = null;
    public static final DebuffHeal BANDAGE = null;
    public static final ItemHeal ANALGETICS = null;
    public static final ItemHeal STEREOIDS = null;
    public static final ItemHeal ADRENALINE = null;
    public static final ItemHeal PAINKILLERS = null;
    public static final ItemHeal MORPHINE = null;
    public static final ItemAmmo WOODEN_AMMO_9MM = null;
    public static final ItemAmmo WOODEN_AMMO_45ACP = null;
    public static final ItemAmmo WOODEN_AMMO_556MM = null;
    public static final ItemAmmo WOODEN_AMMO_762MM = null;
    public static final ItemAmmo WOODEN_AMMO_12G = null;
    public static final ItemAmmo WOODEN_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo STONE_AMMO_9MM = null;
    public static final ItemAmmo STONE_AMMO_45ACP = null;
    public static final ItemAmmo STONE_AMMO_556MM = null;
    public static final ItemAmmo STONE_AMMO_762MM = null;
    public static final ItemAmmo STONE_AMMO_12G = null;
    public static final ItemAmmo STONE_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo IRON_AMMO_9MM = null;
    public static final ItemAmmo IRON_AMMO_45ACP = null;
    public static final ItemAmmo IRON_AMMO_556MM = null;
    public static final ItemAmmo IRON_AMMO_762MM = null;
    public static final ItemAmmo IRON_AMMO_12G = null;
    public static final ItemAmmo IRON_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo GOLD_AMMO_9MM = null;
    public static final ItemAmmo GOLD_AMMO_45ACP = null;
    public static final ItemAmmo GOLD_AMMO_556MM = null;
    public static final ItemAmmo GOLD_AMMO_762MM = null;
    public static final ItemAmmo GOLD_AMMO_12G = null;
    public static final ItemAmmo GOLD_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo DIAMOND_AMMO_9MM = null;
    public static final ItemAmmo DIAMOND_AMMO_45ACP = null;
    public static final ItemAmmo DIAMOND_AMMO_556MM = null;
    public static final ItemAmmo DIAMOND_AMMO_762MM = null;
    public static final ItemAmmo DIAMOND_AMMO_12G = null;
    public static final ItemAmmo DIAMOND_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo EMERALD_AMMO_9MM = null;
    public static final ItemAmmo EMERALD_AMMO_45ACP = null;
    public static final ItemAmmo EMERALD_AMMO_556MM = null;
    public static final ItemAmmo EMERALD_AMMO_762MM = null;
    public static final ItemAmmo EMERALD_AMMO_12G = null;
    public static final ItemAmmo EMERALD_AMMO_CROSSBOW_BOLT = null;
    public static final ItemAmmo AMETHYST_AMMO_9MM = null;
    public static final ItemAmmo AMETHYST_AMMO_45ACP = null;
    public static final ItemAmmo AMETHYST_AMMO_556MM = null;
    public static final ItemAmmo AMETHYST_AMMO_762MM = null;
    public static final ItemAmmo AMETHYST_AMMO_12G = null;
    public static final ItemAmmo AMETHYST_AMMO_CROSSBOW_BOLT = null;
    public static final GRPGItem SMALL_BULLET_CASING = null;
    public static final GRPGItem LARGE_BULLET_CASING = null;
    public static final GRPGItem SHOTGUN_SHELL = null;
    public static final GRPGItem BARREL = null;
    public static final GRPGItem LONG_BARREL = null;
    public static final GRPGItem IRON_STOCK = null;
    public static final GRPGItem SMALL_IRON_STOCK = null;
    public static final GRPGItem WOODEN_STOCK = null;
    public static final GRPGItem MAGAZINE = null;
    public static final GRPGItem GUN_PARTS = null;
    public static final GRPGItem BOLT_FLETCHING = null;
    public static final ItemGrenade GRENADE = null;
    public static final ItemGrenade MASSIVE_GRENADE = null;
    public static final ItemGrenade IMPACT_GRENADE = null;
    public static final GRPGItem IRON_ORE_CHUNK = null;
    public static final GRPGItem GOLD_ORE_CHUNK = null;
    public static final ItemSkillBook SKILLPOINT_BOOK = null;
    public static final ItemHammer WOODEN_HAMMER = null;
    public static final ItemHammer STONE_HAMMER = null;
    public static final ItemHammer IRON_HAMMER = null;
    public static final GRPGItem GOLD_EGG_SHARD = null;
    public static final GRPGItem BLAZE_LUMP = null;
    public static final ItemModdedFood BACON_BURGER = null;
    public static final ItemModdedFood FISH_AND_CHIPS = null;
    public static final ItemModdedFood GARDEN_SOUP = null;
    public static final ItemModdedFood CHICKEN_DINNER = null;
    public static final ItemModdedFood DELUXE_MEAL = null;
    public static final ItemModdedFood MEATY_STEW_XXL = null;
    public static final ItemModdedFood RABBIT_CREAMY_SOUP = null;
    public static final ItemModdedFood SHEPHERDS_PIE = null;
    public static final ItemModdedFood FRUIT_SALAD = null;
    public static final ItemModdedFood EGG_SALAD = null;
    public static final ItemModdedFood CHOCOLATE_GLAZED_APPLE_PIE = null;
}
