package dev.toma.gunsrpg.common.init;

import dev.toma.gunsrpg.GunsRPG;
import dev.toma.gunsrpg.common.item.*;
import dev.toma.gunsrpg.common.item.guns.GunItem;
import dev.toma.gunsrpg.common.item.guns.ammo.AmmoItem;
import dev.toma.gunsrpg.common.item.heal.AttributeAccessHealItem;
import dev.toma.gunsrpg.common.item.heal.ContinuousHealingItem;
import dev.toma.gunsrpg.common.item.heal.DebuffHealItem;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(GunsRPG.MODID)
public class ModItems {
    public static final GunItem M1911 = null;
    public static final GunItem R45 = null;
    public static final GunItem DESERT_EAGLE = null;
    public static final GunItem UMP45 = null;
    public static final GunItem THOMPSON = null;
    public static final GunItem VECTOR = null;
    public static final GunItem AKM = null;
    public static final GunItem HK416 = null;
    public static final GunItem AUG = null;
    public static final GunItem SKS = null;
    public static final GunItem VSS = null;
    public static final GunItem MK14EBR = null;
    public static final GunItem KAR98K = null;
    public static final GunItem WINCHESTER = null;
    public static final GunItem AWM = null;
    public static final GunItem S1897 = null;
    public static final GunItem S686 = null;
    public static final GunItem S12K = null;
    public static final GunItem WOODEN_CROSSBOW = null;
    public static final GunItem CHUKONU = null;
    public static final GunItem GRENADE_LAUNCHER = null;
    public static final GunItem ROCKET_LAUNCHER = null;
    public static final BaseItem AMETHYST = null;
    public static final DebuffHealItem ANTIDOTUM_PILLS = null;
    public static final DebuffHealItem VACCINE = null;
    public static final AttributeAccessHealItem HEMOSTAT = null;
    public static final AttributeAccessHealItem VITAMINS = null;
    public static final AttributeAccessHealItem PROPITAL = null;
    public static final AttributeAccessHealItem CALCIUM_SHOT = null;
    public static final ContinuousHealingItem UFAK = null;
    public static final ContinuousHealingItem KODIAK = null;
    public static final AmmoItem WOODEN_9MM = null;
    public static final AmmoItem WOODEN_45ACP = null;
    public static final AmmoItem WOODEN_556MM = null;
    public static final AmmoItem WOODEN_762MM = null;
    public static final AmmoItem WOODEN_12G = null;
    public static final AmmoItem WOODEN_BOLT = null;
    public static final AmmoItem STONE_9MM = null;
    public static final AmmoItem STONE_45ACP = null;
    public static final AmmoItem STONE_556MM = null;
    public static final AmmoItem STONE_762MM = null;
    public static final AmmoItem STONE_12G = null;
    public static final AmmoItem STONE_BOLT = null;
    public static final AmmoItem IRON_9MM = null;
    public static final AmmoItem IRON_45ACP = null;
    public static final AmmoItem IRON_556MM = null;
    public static final AmmoItem IRON_762MM = null;
    public static final AmmoItem IRON_12G = null;
    public static final AmmoItem IRON_BOLT = null;
    public static final AmmoItem GOLD_9MM = null;
    public static final AmmoItem GOLD_45ACP = null;
    public static final AmmoItem GOLD_556MM = null;
    public static final AmmoItem GOLD_762MM = null;
    public static final AmmoItem GOLD_12G = null;
    public static final AmmoItem GOLD_BOLT = null;
    public static final AmmoItem DIAMOND_9MM = null;
    public static final AmmoItem DIAMOND_45ACP = null;
    public static final AmmoItem DIAMOND_556MM = null;
    public static final AmmoItem DIAMOND_762MM = null;
    public static final AmmoItem DIAMOND_12G = null;
    public static final AmmoItem DIAMOND_BOLT = null;
    public static final AmmoItem EMERALD_9MM = null;
    public static final AmmoItem EMERALD_45ACP = null;
    public static final AmmoItem EMERALD_556MM = null;
    public static final AmmoItem EMERALD_762MM = null;
    public static final AmmoItem EMERALD_12G = null;
    public static final AmmoItem EMERALD_BOLT = null;
    public static final AmmoItem AMETHYST_9MM = null;
    public static final AmmoItem AMETHYST_45ACP = null;
    public static final AmmoItem AMETHYST_556MM = null;
    public static final AmmoItem AMETHYST_762MM = null;
    public static final AmmoItem AMETHYST_12G = null;
    public static final AmmoItem AMETHYST_BOLT = null;
    public static final BaseItem SMALL_BULLET_CASING = null;
    public static final BaseItem LARGE_BULLET_CASING = null;
    public static final BaseItem SHOTGUN_SHELL = null;
    public static final BaseItem BARREL = null;
    public static final BaseItem LONG_BARREL = null;
    public static final BaseItem IRON_STOCK = null;
    public static final BaseItem SMALL_IRON_STOCK = null;
    public static final BaseItem WOODEN_STOCK = null;
    public static final BaseItem MAGAZINE = null;
    public static final BaseItem GUN_PARTS = null;
    public static final BaseItem BOLT_FLETCHING = null;
    public static final GrenadeItem GRENADE = null;
    public static final GrenadeItem MASSIVE_GRENADE = null;
    public static final GrenadeItem IMPACT_GRENADE = null;
    public static final BaseItem IRON_ORE_CHUNK = null;
    public static final BaseItem GOLD_ORE_CHUNK = null;
    public static final PointAwardItem SKILLPOINT_BOOK = null;
    public static final PointAwardItem PERKPOINT_BOOK = null;
    public static final HammerItem WOODEN_HAMMER = null;
    public static final HammerItem STONE_HAMMER = null;
    public static final HammerItem IRON_HAMMER = null;
    public static final BaseItem GOLD_EGG_SHARD = null;
    public static final BaseItem BLAZE_LUMP = null;
    public static final ModFoodItem BACON_BURGER = null;
    public static final ModFoodItem FISH_AND_CHIPS = null;
    public static final ModFoodItem GARDEN_SOUP = null;
    public static final ModFoodItem CHICKEN_DINNER = null;
    public static final ModFoodItem DELUXE_MEAL = null;
    public static final ModFoodItem MEATY_STEW_XXL = null;
    public static final ModFoodItem RABBIT_CREAMY_SOUP = null;
    public static final ModFoodItem SHEPHERDS_PIE = null;
    public static final ModFoodItem FRUIT_SALAD = null;
    public static final ModFoodItem EGG_SALAD = null;
    public static final ModFoodItem CHOCOLATE_GLAZED_APPLE_PIE = null;
    public static final StorageItem LUNCH_BOX = null;
    public static final StorageItem AMMO_CASE = null;
    public static final StorageItem GRENADE_CASE = null;
    public static final StorageItem MEDS_CASE = null;
    public static final StorageItem ITEM_CASE = null;
    public static final CookingOilItem COOKING_OIL = null;
    public static final BaseItem SMALL_STONE = null;
    public static final StarterGearItem STARTER_GEAR = null;
    public static final BaseItem WEAPON_REPAIR_KIT = null;
    public static final StashDetectorItem STASH_DETECTOR = null;
    public static final BaseItem BATTERY = null;
}
