package dev.toma.gunsrpg.common.init;

import dev.toma.gunsrpg.GunsRPG;
import dev.toma.gunsrpg.common.item.*;
import dev.toma.gunsrpg.common.item.guns.GunItem;
import dev.toma.gunsrpg.common.item.guns.ammo.AmmoItem;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(GunsRPG.MODID)
public class ModItems {
    public static final GunItem PISTOL = null;
    public static final GunItem SMG = null;
    public static final GunItem ASSAULT_RIFLE = null;
    public static final GunItem SNIPER_RIFLE = null;
    public static final GunItem SHOTGUN = null;
    public static final GunItem CROSSBOW = null;
    public static final BaseItem AMETHYST = null;
    public static final DebuffHealItem ANTIDOTUM_PILLS = null;
    public static final DebuffHealItem VACCINE = null;
    public static final DebuffHealItem PLASTER_CAST = null;
    public static final DebuffHealItem BANDAGE = null;
    public static final PlayerHealItem ANALGETICS = null;
    public static final PlayerHealItem STEREOIDS = null;
    public static final PlayerHealItem ADRENALINE = null;
    public static final PlayerHealItem PAINKILLERS = null;
    public static final PlayerHealItem MORPHINE = null;
    public static final AmmoItem WOODEN_AMMO_9MM = null;
    public static final AmmoItem WOODEN_AMMO_45ACP = null;
    public static final AmmoItem WOODEN_AMMO_556MM = null;
    public static final AmmoItem WOODEN_AMMO_762MM = null;
    public static final AmmoItem WOODEN_AMMO_12G = null;
    public static final AmmoItem WOODEN_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem STONE_AMMO_9MM = null;
    public static final AmmoItem STONE_AMMO_45ACP = null;
    public static final AmmoItem STONE_AMMO_556MM = null;
    public static final AmmoItem STONE_AMMO_762MM = null;
    public static final AmmoItem STONE_AMMO_12G = null;
    public static final AmmoItem STONE_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem IRON_AMMO_9MM = null;
    public static final AmmoItem IRON_AMMO_45ACP = null;
    public static final AmmoItem IRON_AMMO_556MM = null;
    public static final AmmoItem IRON_AMMO_762MM = null;
    public static final AmmoItem IRON_AMMO_12G = null;
    public static final AmmoItem IRON_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem GOLD_AMMO_9MM = null;
    public static final AmmoItem GOLD_AMMO_45ACP = null;
    public static final AmmoItem GOLD_AMMO_556MM = null;
    public static final AmmoItem GOLD_AMMO_762MM = null;
    public static final AmmoItem GOLD_AMMO_12G = null;
    public static final AmmoItem GOLD_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem DIAMOND_AMMO_9MM = null;
    public static final AmmoItem DIAMOND_AMMO_45ACP = null;
    public static final AmmoItem DIAMOND_AMMO_556MM = null;
    public static final AmmoItem DIAMOND_AMMO_762MM = null;
    public static final AmmoItem DIAMOND_AMMO_12G = null;
    public static final AmmoItem DIAMOND_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem EMERALD_AMMO_9MM = null;
    public static final AmmoItem EMERALD_AMMO_45ACP = null;
    public static final AmmoItem EMERALD_AMMO_556MM = null;
    public static final AmmoItem EMERALD_AMMO_762MM = null;
    public static final AmmoItem EMERALD_AMMO_12G = null;
    public static final AmmoItem EMERALD_AMMO_CROSSBOW_BOLT = null;
    public static final AmmoItem AMETHYST_AMMO_9MM = null;
    public static final AmmoItem AMETHYST_AMMO_45ACP = null;
    public static final AmmoItem AMETHYST_AMMO_556MM = null;
    public static final AmmoItem AMETHYST_AMMO_762MM = null;
    public static final AmmoItem AMETHYST_AMMO_12G = null;
    public static final AmmoItem AMETHYST_AMMO_CROSSBOW_BOLT = null;
    public static final BaseItem SMALL_BULLET_CASING = null;
    public static final BaseItem LARGE_BULLET_CASING = null;
    public static final BaseItem SHOTGUN_SHELL = null;
    public static final BaseItem BARREL = null;
    public static final BaseItem LONG_BARREL = null;
    public static final BaseItem IRON_STOCK = null;
    public static final BaseItem SMALL_IRON_STOCK = null;
    public static final BaseItem WOODEN_STOCK = null;
    public static final BaseItem MAGAZINE = null;
    public static final BaseItem GUN_PARTS = null;
    public static final BaseItem BOLT_FLETCHING = null;
    public static final GrenadeItem GRENADE = null;
    public static final GrenadeItem MASSIVE_GRENADE = null;
    public static final GrenadeItem IMPACT_GRENADE = null;
    public static final BaseItem IRON_ORE_CHUNK = null;
    public static final BaseItem GOLD_ORE_CHUNK = null;
    public static final SkillBookItem SKILLPOINT_BOOK = null;
    public static final HammerItem WOODEN_HAMMER = null;
    public static final HammerItem STONE_HAMMER = null;
    public static final HammerItem IRON_HAMMER = null;
    public static final BaseItem GOLD_EGG_SHARD = null;
    public static final BaseItem BLAZE_LUMP = null;
    public static final ModFoodItem BACON_BURGER = null;
    public static final ModFoodItem FISH_AND_CHIPS = null;
    public static final ModFoodItem GARDEN_SOUP = null;
    public static final ModFoodItem CHICKEN_DINNER = null;
    public static final ModFoodItem DELUXE_MEAL = null;
    public static final ModFoodItem MEATY_STEW_XXL = null;
    public static final ModFoodItem RABBIT_CREAMY_SOUP = null;
    public static final ModFoodItem SHEPHERDS_PIE = null;
    public static final ModFoodItem FRUIT_SALAD = null;
    public static final ModFoodItem EGG_SALAD = null;
    public static final ModFoodItem CHOCOLATE_GLAZED_APPLE_PIE = null;
}
