package dev.toma.gunsrpg.common.init;

import dev.toma.gunsrpg.GunsRPG;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(GunsRPG.MODID)
public class ModSounds {
    public static final SoundEvent PLANE_FLY_BY = null;
    public static final SoundEvent M1911 = null;
    public static final SoundEvent M1911_SILENT = null;
    public static final SoundEvent SKS = null;
    public static final SoundEvent SKS_SILENT = null;
    public static final SoundEvent M9 = null;
    public static final SoundEvent MP5 = null;
    public static final SoundEvent SLR = null;
    public static final SoundEvent M24 = null;
    public static final SoundEvent S686 = null;
    public static final SoundEvent M16 = null;
    public static final SoundEvent FLARE_SHOOT = null;
    public static final SoundEvent SECOND_CHANCE_USE = null;
    public static final SoundEvent RELAXED_2 = null;
    public static final SoundEvent USE_AVENGE_ME_FRIENDS = null;
    public static final SoundEvent USE_WELL_FED = null;
    public static final SoundEvent BULLET_WHIZZ = null;
    public static final SoundEvent GUN_AKM = null;
    public static final SoundEvent GUN_AKM_SILENCED = null;
    public static final SoundEvent GUN_AUG = null;
    public static final SoundEvent GUN_AUG_SILENCED = null;
    public static final SoundEvent GUN_AWM = null;
    public static final SoundEvent GUN_AWM_SILENCED = null;
    public static final SoundEvent CROSSBOW_SHOOT = null;
    public static final SoundEvent GUN_DEAGLE = null;
    public static final SoundEvent GL_SHOT1 = null;
    public static final SoundEvent GUN_M416 = null;
    public static final SoundEvent GUN_M416_SILENCED = null;
    public static final SoundEvent GUN_KAR98K = null;
    public static final SoundEvent GUN_KAR98K_SILENCED = null;
    public static final SoundEvent GUN_MK14 = null;
    public static final SoundEvent GUN_MK14_SILENCED = null;
    public static final SoundEvent GUN_R1895_SILENCED = null;
    public static final SoundEvent GUN_R45 = null;
    public static final SoundEvent RL_LOCKED1 = null;
    public static final SoundEvent RL_SHOT = null;
    public static final SoundEvent GUN_S12K = null;
    public static final SoundEvent GUN_S12K_SILENCED = null;
    public static final SoundEvent GUN_S1897 = null;
    public static final SoundEvent GUN_S686 = null;
    public static final SoundEvent GUN_TOMMY_GUN = null;
    public static final SoundEvent GUN_TOMMY_GUN_SILENCED = null;
    public static final SoundEvent GUN_UMP9 = null;
    public static final SoundEvent GUN_UMP9_SILENCED = null;
    public static final SoundEvent GUN_VECTOR = null;
    public static final SoundEvent GUN_VECTOR_SILENCED = null;
    public static final SoundEvent GUN_VSS = null;
    public static final SoundEvent GUN_WIN94 = null;
    public static final SoundEvent REPAIR = null;
    public static final SoundEvent DETECTOR_BEEP = null;
    public static final SoundEvent DETECTOR_BEEP_LONG = null;
}
