package dev.toma.gunsrpg.common.init;

import dev.toma.gunsrpg.GunsRPG;
import dev.toma.gunsrpg.api.common.skill.ISkill;
import dev.toma.gunsrpg.common.skills.*;
import dev.toma.gunsrpg.common.skills.core.SkillType;
import net.minecraftforge.registries.ObjectHolder;

@ObjectHolder(GunsRPG.MODID)
public class Skills {
    public static final SkillType<BasicSkill> WOODEN_AMMO_SMITH = null;
    public static final SkillType<BasicSkill> M1911_ASSEMBLY = null;
    public static final SkillType<BasicSkill> R45_ASSEMBLY = null;
    public static final SkillType<BasicSkill> DESERT_EAGLE_ASSEMBLY = null;
    public static final SkillType<BasicSkill> UMP45_ASSEMBLY = null;
    public static final SkillType<BasicSkill> THOMPSON_ASSEMBLY = null;
    public static final SkillType<BasicSkill> VECTOR_ASSEMBLY = null;
    public static final SkillType<BasicSkill> AKM_ASSEMBLY = null;
    public static final SkillType<BasicSkill> HK416_ASSEMBLY = null;
    public static final SkillType<BasicSkill> AUG_ASSEMBLY = null;
    public static final SkillType<BasicSkill> CROSSBOW_ASSEMBLY = null;
    public static final SkillType<BasicSkill> CHUKONU_ASSEMBLY = null;
    public static final SkillType<BasicSkill> S1897_ASSEMBLY = null;
    public static final SkillType<BasicSkill> S686_ASSEMBLY = null;
    public static final SkillType<BasicSkill> S12K_ASSEMBLY = null;
    public static final SkillType<BasicSkill> SKS_ASSEMBLY = null;
    public static final SkillType<BasicSkill> VSS_ASSEMBLY = null;
    public static final SkillType<BasicSkill> MK14EBR_ASSEMBLY = null;
    public static final SkillType<BasicSkill> KAR98K_ASSEMBLY = null;
    public static final SkillType<BasicSkill> WINCHESTER_ASSEMBLY = null;
    public static final SkillType<BasicSkill> AWM_ASSEMBLY = null;
    public static final SkillType<BasicSkill> GRENADE_LAUNCHER_ASSEMBLY = null;
    public static final SkillType<BasicSkill> ROCKET_LAUNCHER_ASSEMBLY = null;
    public static final SkillType<BasicSkill> EFFICIENT_MEDS = null;
    public static final SkillType<LumberjackSkill> LUMBERJACK_I = null;
    public static final SkillType<MotherlodeSkill> MOTHER_LODE_I = null;
    public static final SkillType<BasicSkill> BLACKSMITH = null;
    public static final SkillType<WellFedSkill> WELL_FED_I = null;
    public static final SkillType<SecondChanceSkill> SECOND_CHANCE_I = null;
    public static final SkillType<SecondChanceSkill> SECOND_CHANCE_II = null;
    public static final SkillType<SecondChanceSkill> SECOND_CHANCE_III = null;
    public static final SkillType<AdrenalineRushSkill> ADRENALINE_RUSH_I = null;
    public static final SkillType<GodHelpUsSkill> GOD_HELP_US = null;
    public static final SkillType<LightHunterSkill> LIGHT_HUNTER = null;
    public static final SkillType<AvengeMeFriendsSkill> AVENGE_ME_FRIENDS = null;
    public static final SkillType<LikeACatSkill> LIKE_A_CAT_I = null;
    public static final SkillType<LikeACatSkill> LIKE_A_CAT_II = null;
    public static final SkillType<LikeACatSkill> LIKE_A_CAT_III = null;
    public static final SkillType<IronBuddySkill> IRON_BUDDY_I = null;
    public static final SkillType<IronBuddySkill> IRON_BUDDY_II = null;
    public static final SkillType<IronBuddySkill> IRON_BUDDY_III = null;
    public static final SkillType<WarMachineSkill> WAR_MACHINE = null;
    public static final SkillType<TreasureHunterSkill> TREASURE_HUNTER_I = null;
    public static final SkillType<BasicSkill> CRYSTALIZED = null;
    public static final SkillType<ISkill> M1911_SUPPRESSOR = null;
    public static final SkillType<ISkill> M1911_HEAVY_BULLETS = null;
    public static final SkillType<ISkill> M1911_KILLING_SPREE = null;
    public static final SkillType<ISkill> R45_SUPPRESSOR = null;
    public static final SkillType<ISkill> R45_ACE_OF_HEARTS = null;
    public static final SkillType<ISkill> R45_EVERY_BULLET_COUNTS = null;
    public static final SkillType<ISkill> DEAGLE_RED_DOT = null;
    public static final SkillType<ISkill> DEAGLE_PENETRATOR = null;
    public static final SkillType<ISkill> DEAGLE_FINISHER = null;
    public static final SkillType<ISkill> UMP45_RED_DOT = null;
    public static final SkillType<ISkill> UMP45_SUPPRESSOR = null;
    public static final SkillType<ISkill> UMP45_COMMANDO = null;
    public static final SkillType<ISkill> THOMPSON_SUPPRESSOR = null;
    public static final SkillType<ISkill> THOMPSON_EXTENDED = null;
    public static final SkillType<ISkill> THOMPSON_RED_DOT = null;
    public static final SkillType<ISkill> THOMPSON_SOUL_TAKER = null;
    public static final SkillType<ISkill> VECTOR_SUPPRESSOR = null;
    public static final SkillType<ISkill> VECTOR_RED_DOT = null;
    public static final SkillType<ISkill> VECTOR_OVERLOADED = null;
    public static final SkillType<ISkill> CROSSBOW_POISONED_BOLTS = null;
    public static final SkillType<ISkill> CROSSBOW_HUNTER = null;
    public static final SkillType<ISkill> CROSSBOW_PENETRATOR = null;
    public static final SkillType<ISkill> CROSSBOW_TOUGH_BOWSTRING = null;
    public static final SkillType<ISkill> CROSSBOW_SCOPE = null;
    public static final SkillType<ISkill> CHUKONU_POISONED_BOLTS = null;
    public static final SkillType<ISkill> CHUKONU_TOUGH_BOWSTRING = null;
    public static final SkillType<ISkill> CHUKONU_SCOPE = null;
    public static final SkillType<ISkill> CHUKONU_HEAVY_BOLTS = null;
    public static final SkillType<ISkill> S1897_BULLET_LOOPS = null;
    public static final SkillType<ISkill> S1897_EXTENDED = null;
    public static final SkillType<ISkill> S1897_PUMP_IN_ACTION = null;
    public static final SkillType<ISkill> S1897_CHOKE = null;
    public static final SkillType<ISkill> S1897_NEVER_GIVE_UP = null;
    public static final SkillType<ISkill> S1897_EXTENDED_BARREL = null;
    public static final SkillType<ISkill> S686_CANNON_BLAST = null;
    public static final SkillType<ISkill> S12K_SUPPRESSOR = null;
    public static final SkillType<ISkill> AKM_SUPPRESSOR = null;
    public static final SkillType<ISkill> HK416_SUPPRESSOR = null;
    public static final SkillType<ISkill> AUG_SUPPRESSOR = null;
    public static final SkillType<ISkill> SKS_TOUGH_SPRING = null;
    public static final SkillType<ISkill> SKS_VERTICAL_GRIP = null;
    public static final SkillType<ISkill> SKS_EXTENDED = null;
    public static final SkillType<ISkill> SKS_RED_DOT = null;
    public static final SkillType<ISkill> SKS_SUPPRESSOR = null;
    public static final SkillType<ISkill> SKS_CHEEKPAD = null;
    public static final SkillType<ISkill> SKS_ADAPTIVE_CHAMBERING = null;
    public static final SkillType<ISkill> VSS_ADAPTIVE_CHAMBERING = null;
    public static final SkillType<ISkill> MK14EBR_SUPPRESSOR = null;
    public static final SkillType<ISkill> KAR98K_SCOPE = null;
    public static final SkillType<ISkill> KAR98K_CHEEKPAD = null;
    public static final SkillType<ISkill> KAR98K_EXTENDED = null;
    public static final SkillType<ISkill> KAR98K_SUPPRESSOR = null;
    public static final SkillType<ISkill> KAR98K_FAST_HANDS = null;
    public static final SkillType<ISkill> KAR98K_PENETRATOR = null;
    public static final SkillType<ISkill> KAR98K_DEAD_EYE = null;
    public static final SkillType<ISkill> AWM_SUPPRESSOR = null;
    public static final SkillType<ISkill> ROCKET_LAUNCHER_ROCKET_BARRAGE = null;
}
